#!/usr/bin/python3
"""Defines the Base class, the root of the hierarchy for this project."""
import json
import csv


class Base:
    """Manage the id attribute for all future classes.

    This class is the "base" of all other classes in this project.
    It manages the id attribute of every instance, and provides
    class/static methods to serialize and deserialize instances
    to and from JSON or CSV, and to and from files on disk.
    """

    __nb_objects = 0

    def __init__(self, id=None):
        """Initialize a new Base instance.

        Args:
            id (int): The identity of the new instance. If None,
                the id is auto-generated by incrementing the
                private class attribute __nb_objects.
        """
        if id is not None:
            self.id = id
        else:
            Base.__nb_objects += 1
            self.id = Base.__nb_objects

    @staticmethod
    def to_json_string(list_dictionaries):
        """Return the JSON string representation of a list of dicts.

        Args:
            list_dictionaries (list): A list of dictionaries.

        Returns:
            str: The JSON string representation of list_dictionaries,
                or "[]" if list_dictionaries is None or empty.
        """
        if list_dictionaries is None or len(list_dictionaries) == 0:
            return "[]"
        return json.dumps(list_dictionaries)

    @classmethod
    def save_to_file(cls, list_objs):
        """Write the JSON string representation of list_objs to a file.

        The filename used is <Class name>.json, and it is
        overwritten if it already exists.

        Args:
            list_objs (list): A list of instances that inherit
                from Base.
        """
        filename = cls.__name__ + ".json"
        if list_objs is None:
            list_objs = []
        list_dicts = [obj.to_dictionary() for obj in list_objs]
        with open(filename, "w") as jsonfile:
            jsonfile.write(cls.to_json_string(list_dicts))

    @staticmethod
    def from_json_string(json_string):
        """Return the list represented by a JSON string.

        Args:
            json_string (str): A string representing a list of
                dictionaries.

        Returns:
            list: The list represented by json_string, or an empty
                list if json_string is None or empty.
        """
        if json_string is None or len(json_string) == 0:
            return []
        return json.loads(json_string)

    @classmethod
    def create(cls, **dictionary):
        """Return an instance with all attributes already set.

        Args:
            **dictionary: Key/value pairs of attributes to
                initialize the new instance with.

        Returns:
            An instance of cls with attributes set from dictionary.
        """
        if cls.__name__ == "Rectangle":
            dummy = cls(1, 1)
        else:
            dummy = cls(1)
        dummy.update(**dictionary)
        return dummy

    @classmethod
    def load_from_file(cls):
        """Return a list of instances loaded from a file.

        The filename used is <Class name>.json.

        Returns:
            list: A list of instances of cls, or an empty list if
                the file doesn't exist.
        """
        filename = cls.__name__ + ".json"
        try:
            with open(filename, "r") as jsonfile:
                list_dicts = cls.from_json_string(jsonfile.read())
                return [cls.create(**d) for d in list_dicts]
        except IOError:
            return []

    @classmethod
    def save_to_file_csv(cls, list_objs):
        """Write the CSV representation of list_objs to a file.

        The filename used is <Class name>.csv, and it is
        overwritten if it already exists. Each row holds an
        instance's to_dictionary() values in order, so the format
        is <id>,<width>,<height>,<x>,<y> for Rectangle and
        <id>,<size>,<x>,<y> for Square.

        Args:
            list_objs (list): A list of instances that inherit
                from Base.
        """
        filename = cls.__name__ + ".csv"
        if list_objs is None:
            list_objs = []
        with open(filename, "w", newline="") as csvfile:
            writer = csv.writer(csvfile)
            for obj in list_objs:
                writer.writerow(list(obj.to_dictionary().values()))

    @classmethod
    def load_from_file_csv(cls):
        """Return a list of instances loaded from a CSV file.

        The filename used is <Class name>.csv. Rows are mapped
        back to dictionaries using the field order
        id,width,height,x,y for Rectangle and id,size,x,y for
        Square, then rebuilt into instances via create().

        Returns:
            list: A list of instances of cls, or an empty list if
                the file doesn't exist.
        """
        filename = cls.__name__ + ".csv"
        if cls.__name__ == "Rectangle":
            keys = ["id", "width", "height", "x", "y"]
        else:
            keys = ["id", "size", "x", "y"]
        try:
            with open(filename, "r", newline="") as csvfile:
                reader = csv.reader(csvfile)
                list_dicts = [
                    {k: int(v) for k, v in zip(keys, row)}
                    for row in reader
                ]
                return [cls.create(**d) for d in list_dicts]
        except IOError:
            return []
